# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Castor_Armatuur_Paal_Koppelen.py
# Created on: 2021-12-07 15:52:48.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Inrichtend = "Inrichtend"
Armatuur = Inrichtend
Copy_Armatuur = "in_memory\\Copy_Armatuur"
Copy_Armatuur_Buffer = "in_memory\\Copy_Armatuur_Buffer"
Inrichtend__2_ = "Inrichtend"
Paal = Inrichtend__2_
Copy_Paal = "in_memory\\Copy_Paal"
Copy_Armatuur_Buffer_Spatial = "in_memory\\Copy_Armatuur_Buffer_Spatial"

# Process: Select Data Armatuur
arcpy.SelectData_management(Inrichtend, "Armatuur")

# Process: Copy Features Armatuur
arcpy.CopyFeatures_management(Armatuur, Copy_Armatuur, "", "0", "0", "0")

# Process: Buffer
arcpy.Buffer_analysis(Copy_Armatuur, Copy_Armatuur_Buffer, "0,5 Meters", "FULL", "ROUND", "NONE", "", "PLANAR")

# Process: Select Data Paal
arcpy.SelectData_management(Inrichtend__2_, "Paal")

# Process: Copy Features Paal
arcpy.CopyFeatures_management(Paal, Copy_Paal, "", "0", "0", "0")

# Process: Spatial Join
arcpy.SpatialJoin_analysis(Copy_Armatuur_Buffer, Copy_Paal, Copy_Armatuur_Buffer_Spatial, "JOIN_ONE_TO_ONE", "KEEP_ALL", "BOR_ID_ARMA \"BOR_ID\" true true false 50 Text 0 0 ,First,#,in_memory\\Copy_Armatuur_Buffer,BOR_ID,-1,-1;POLE_REF_ARMA \"POLE_REF\" true true false 50 Text 0 0 ,First,#,in_memory\\Copy_Armatuur_Buffer,POLE_REF,-1,-1;TYPE_PAAL \"TYPE\" true true false 50 Text 0 0 ,First,#,in_memory\\Copy_Paal,TYPE,-1,-1;BOR_ID_PAAL \"BOR_ID\" true true false 50 Text 0 0 ,First,#,in_memory\\Copy_Paal,BOR_ID,-1,-1;WVK_ID_PAAL \"WVK_ID\" true true false 4 Long 0 10 ,First,#,in_memory\\Copy_Paal,WVK_ID,-1,-1;POLE_NUMBER_PAAL \"POLE_NUMBER\" true true false 50 Text 0 0 ,First,#,in_memory\\Copy_Paal,POLE_NUMBER,-1,-1;GLOBALID_PAAL \"GLOBALID\" true false false 38 GlobalID 0 0 ,First,#,in_memory\\Copy_Paal,GLOBALID,-1,-1", "CLOSEST", "", "DIST")

